// A real batch of Malian pharmacies (rows #490-654 of a national registry
// you provided) — embedded here so importing them is a single click from
// Super Admin, rather than needing to paste a CSV by hand. Four rows
// needed manual correction during parsing (two had wrapped multi-line
// names in the original source, two had missing/ambiguous région data —
// see conversation notes for exactly what was inferred and why). This is
// a real 161-entry batch, NOT the complete national list — rows #1-489
// weren't provided and would need a separate import if you get them.
export const PHARMACIES_SEED = [
  { name: "OFFICINE AGUIBOU SYLLA", address: "Wayerma", commune: "Sikasso", ville: "Sikasso", phone: "", responsiblePerson: "M. SYLLA Aguibou" },
  { name: "OFFICINE SARANKE AWA TOURE", address: "Wayerma", commune: "Sikasso", ville: "Sikasso", phone: "", responsiblePerson: "M. TOURE Sarankè Awa" },
  { name: "OFFICINE YAYA SOGODOGO", address: "Wayerma", commune: "Sikasso", ville: "Sikasso", phone: "", responsiblePerson: "M. SOGODOGO Yaya" },
  { name: "OFFICINE JOSEPH MEDINE SANTE", address: "Hamdallaye-Sikasso", commune: "Sikasso", ville: "Sikasso", phone: "", responsiblePerson: "M. YARO Bouréïma" },
  { name: "OFFICINE DADY DIOP", address: "Wayerma II", commune: "Sikasso", ville: "Sikasso", phone: "", responsiblePerson: "Ibrahima KAMPO" },
  { name: "OFFICINE NENE", address: "Hamdallaye", commune: "Sikasso", ville: "Sikasso", phone: "", responsiblePerson: "Daouda Bakary SANGARE" },
  { name: "OFFICINE PAPA DOUGOUNOU", address: "Mamassoni", commune: "Sikasso", ville: "Sikasso", phone: "", responsiblePerson: "M. Fousseni COULIBALY" },
  { name: "OFFICINE HADOU", address: "Sortie vers Koutiala", commune: "Sikasso", ville: "Sikasso", phone: "", responsiblePerson: "M. Aly Hadou DIALLO" },
  { name: "OFFICINE GRACE DIVINE", address: "Lafiabougou Ext", commune: "Sikasso", ville: "Sikasso", phone: "", responsiblePerson: "Mme Amité Roseline DAKOUO" },
  { name: "OFFICINE SENDE CAMARA", address: "Finkolo Ganadougou", commune: "Sikasso", ville: "Sikasso", phone: "", responsiblePerson: "M. Sékou DOUCOURE" },
  { name: "OFFICINE AÏCHA", address: "Sikasso, Quartier Banconi", commune: "Sikasso", ville: "Sikasso", phone: "", responsiblePerson: "M. Abdoul Karim BERTHE" },
  { name: "OFFICINE NABINTOU KONE", address: "Nakoun Diassa", commune: "Sikasso", ville: "Sikasso", phone: "", responsiblePerson: "M. Ousmane Ibrahim MAÏGA" },
  { name: "OFFICINE SEGUINA", address: "Kangaré", commune: "Yanfolila", ville: "Sikasso", phone: "", responsiblePerson: "M. KONATE Nouhoum" },
  { name: "OFFICINE KARIM TEMBELY", address: "Yanfolila", commune: "Yanfolila", ville: "Sikasso", phone: "", responsiblePerson: "M. TEMBELY Karim" },
  { name: "OFFFICINE DJEDIE BALLO", address: "Binko", commune: "Yanfolila", ville: "Sikasso", phone: "", responsiblePerson: "M. Sossé FANE" },
  { name: "OFFICINE BASALI", address: "Kalana", commune: "Yanfolila", ville: "Sikasso", phone: "", responsiblePerson: "M. Sidiki BERTHE" },
  { name: "OFFICINE BAMINATA COULIBALY", address: "Dalabala", commune: "Yanfolila", ville: "Sikasso", phone: "", responsiblePerson: "M. Zié Drissa OUATTARA" },
  { name: "OFFICINE KANFING TRAORE", address: "Kouri", commune: "Yorosso", ville: "Sikasso", phone: "", responsiblePerson: "M. Kariba dit Ousmane SAMAKE" },
  { name: "OFFICINE TCHÔRO SI TCHOUMON", address: "Yorosso", commune: "Yorosso", ville: "Sikasso", phone: "", responsiblePerson: "Mme Sira Alice DIOMAN" },
  { name: "OFFICINE KADIA DEMBELE", address: "Mahou", commune: "Yorosso", ville: "Sikasso", phone: "", responsiblePerson: "M. Yaya Demba BERTHE" },
  { name: "OFFICINE MAMOUROU DIAKITE", address: "Markéïna 1", commune: "Bla", ville: "Ségou", phone: "", responsiblePerson: "M. DIAKITE Mamourou" },
  { name: "OFFICINE ASSABA DICKO", address: "Bla", commune: "Bla", ville: "Ségou", phone: "", responsiblePerson: "Dr Mohamed Ag Mohamed" },
  { name: "OFFICINE AIDA", address: "Yangasso", commune: "Bla", ville: "Ségou", phone: "", responsiblePerson: "M. Abdoulaye DIABY" },
  { name: "OFFICINE SADIAN KOUMA", address: "Barouéli", commune: "Barouéli", ville: "Ségou", phone: "", responsiblePerson: "M. KOUMA Sadian" },
  { name: "OFFICINE BARON", address: "Konobougou", commune: "Barouéli", ville: "Ségou", phone: "", responsiblePerson: "Mlle Fatoumata Oumar OUATTARA" },
  { name: "OFFICINE AL BARKA", address: "Barouéli", commune: "Barouéli", ville: "Ségou", phone: "", responsiblePerson: "M. Amadou KEÏTA" },
  { name: "OFFICINE BWATUN", address: "Barouéli", commune: "Barouéli", ville: "Ségou", phone: "", responsiblePerson: "M. François KAMATE" },
  { name: "OFFICINE TAMA-PHARM", address: "Tamani", commune: "Barouéli", ville: "Ségou", phone: "", responsiblePerson: "M. Oumar NIANGADOU" },
  { name: "OFFICINE ANYA", address: "Macina", commune: "Macina", ville: "Ségou", phone: "", responsiblePerson: "M. TALHATA Mahamar" },
  { name: "OFFICINE DO-FINI", address: "Macina", commune: "Macina", ville: "Ségou", phone: "", responsiblePerson: "Mme Zouon Théodorine KONE" },
  { name: "OFFICINE LASSINA SYLLA", address: "Quartier A", commune: "Niono", ville: "Ségou", phone: "", responsiblePerson: "M. SYLLA Lassina" },
  { name: "OFFICINE BOCOUM ALLAYE", address: "Quartier B", commune: "Niono", ville: "Ségou", phone: "", responsiblePerson: "M. BOCOUM Allaye" },
  { name: "OFFICINE ADAM BALLO", address: "Niono", commune: "Niono", ville: "Ségou", phone: "", responsiblePerson: "M. Cheick Oumar KONE" },
  { name: "OFFICINE DJOMINE DEMBELE", address: "Niono", commune: "Niono", ville: "Ségou", phone: "", responsiblePerson: "M. Moumouny DEMBELE" },
  { name: "OFFICINE JIGIYA", address: "Diabali", commune: "Niono", ville: "Ségou", phone: "", responsiblePerson: "M. Lassiné KOUYATE" },
  { name: "OFFICINE SUKALA", address: "Siribala", commune: "Niono", ville: "Ségou", phone: "", responsiblePerson: "M. Drissa DIARRA" },
  { name: "OFICINE LAFIA", address: "Niono", commune: "Niono", ville: "Ségou", phone: "", responsiblePerson: "Mme Kadiatou Datigui DEMBELE" },
  { name: "OFFICINE DANA DEMBELE", address: "Niono", commune: "Niono", ville: "Ségou", phone: "", responsiblePerson: "M. Benjamè COULIBALY" },
  { name: "OFFICINE DOGUELOU DOLO", address: "Niono vers Logs Sociaux", commune: "Niono", ville: "Ségou", phone: "", responsiblePerson: "M. Oumar DOLO" },
  { name: "OFFICINE VERONIQUE DEMBELE", address: "Bagadadji-San", commune: "San", ville: "Ségou", phone: "", responsiblePerson: "Mme. DEMBELE Véronique" },
  { name: "OFFICINE JABIROU A HAIDARA", address: "Lafiabougou-San", commune: "San", ville: "Ségou", phone: "", responsiblePerson: "M. HAÏDARA Jabirou" },
  { name: "OFFICINE KAPOLON", address: "Santoro", commune: "San", ville: "Ségou", phone: "", responsiblePerson: "M. SANOGO Amadou" },
  { name: "OFFICINE MOUGNOU", address: "Lafiabougou-San", commune: "San", ville: "Ségou", phone: "", responsiblePerson: "M. DENA Pakyu" },
  { name: "OFICINE INDAM", address: "San", commune: "San", ville: "Ségou", phone: "", responsiblePerson: "M. Idrissa BAMADIO" },
  { name: "OFICINE ADJARA TRAORE", address: "Kimparana", commune: "San", ville: "Ségou", phone: "", responsiblePerson: "M. Ibrahima TRAORE" },
  { name: "OFFICINE BY DAOU", address: "Tènè", commune: "San", ville: "Ségou", phone: "", responsiblePerson: "M. Siratigui DIARRA" },
  { name: "OFFICINE TALIBE HADJI BAH", address: "San Quartier Hamdallaye", commune: "San", ville: "Ségou", phone: "", responsiblePerson: "M. Elhadji Ibrahim BAH" },
  { name: "PHARMACIE DU MARCHÉ", address: "San Quartier Hamdallaye", commune: "San", ville: "Ségou", phone: "", responsiblePerson: "Mme Fatoumata Bemin TRAORE" },
  { name: "OFFICINE AMIDOU TRAORE", address: "San Quartier Lafiabougou", commune: "San", ville: "Ségou", phone: "", responsiblePerson: "Mme Oumou TRAORE" },
  { name: "OFFICINE SARACOLE", address: "Allamissani", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "Inconnu Inconnu Inconnu" },
  { name: "OFFICINE ABDOULAYE DIARRA", address: "Bagadadji-Ségou", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. TRAORE Mamadou" },
  { name: "OFFICINE KENEYA SEGOU", address: "Darsalam-Ségou", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "Inconnu Inconnu Inconnu" },
  { name: "OFFICINE ALY SOMOUNTERA", address: "Darsalam-Ségou", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. SOUMOUNTERA Aly" },
  { name: "OFFICINE BABEMBA SEGOU", address: "Hamdallaye-Ségou", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. TRAORE Albert" },
  { name: "OFFICINE KOLI", address: "Hamdallaye-Ségou", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. DIARRA Boubacar Koli" },
  { name: "OFFICINE BALANZAN", address: "Médine-Ségou", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. KONE Issa" },
  { name: "OFFICINE SIYATOU Z TOURE", address: "Médine-Ségou", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "Mme. TOURE Siyatou Z" },
  { name: "OFFICINE AMARY DAOU", address: "Missira-Ségou", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. SANGARE Cheick Kader" },
  { name: "OFFICINE CHEICK DEMBELE", address: "Péléngana", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. Boubacar Cheick DEMBELE" },
  { name: "OFFICINE KENEYA-SO", address: "Péléngana", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. DIALLO Maki" },
  { name: "OFFICINE BAMORY", address: "Quartier Administratif", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. SANOGO Mamadou" },
  { name: "OFFICINE AMADOU COULIBALY", address: "Ségou-coura Somono", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. COULIBALY Amadou" },
  { name: "OFFICINE GOGO", address: "Markala", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. TRAORE Sékou Drissa" },
  { name: "OFFICINE ACCUEIL", address: "Hamdallaye", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. Cheick Abdoul Khader TAPO" },
  { name: "OFFICINE DJEMA", address: "Hamdallaye-Ségou", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "Mme. DAFF Fanta" },
  { name: "OFFICINE BAAMI", address: "1er Quartier", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. Abdourahmane SANGARE" },
  { name: "OFFICINE ROND POINT SEGOU", address: "Allamissani", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "Mme KANE Hawa DIAWARA" },
  { name: "OFFICINE MOUSSOUMAKAN DIALLO", address: "Dioro", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. Sory Ibrahima FOMBA" },
  { name: "OFFICINE L'AN 2000", address: "Darsalam Ségou", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. Boubacar DICKO" },
  { name: "OFFICINE PA & MA", address: "Quartier Commercial", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. Cheick Hamallah SEMEGA" },
  { name: "OFFICINE YAYA DEMBELE", address: "Darsalam Ségou", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. Mohamed Zekra DEMBELE" },
  { name: "OFFICINE ARC-EN-CIEL", address: "Ségou Bougoufiè", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. Youssouf Sékou DIARRA" },
  { name: "OFFICINE HATOUMATA YAFFA", address: "Sébougou, Ségou", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. Zoumana DIAKITE" },
  { name: "OFFICINE EL MOUMININE", address: "Sébougou, près du CROU", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. Adama DEMBELE" },
  { name: "OFFICINE SANSANDING", address: "Sansanding", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "Mme Djelika DIABATE" },
  { name: "PHARMACIE ANGOULEME", address: "Quartier Angoulème", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. Michel COULIBALY" },
  { name: "OFFICINE MED PHARM PLUS", address: "Quartier Missira", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. Anou Moïse SOMBORO" },
  { name: "OFFICINE MIEUX VIVRE", address: "Hamdallaye, Dioro", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. Josué KONE" },
  { name: "OFFICINE O.D", address: "Markala", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "Mme Djénébou Oumar TRAORE" },
  { name: "OFFICINE NETIE JOACHIM", address: "Dougabougou", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. Martin SAMAKE" },
  { name: "OFFICINE PAPIS", address: "Pélengana", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "M. Hamadi TRAORE" },
  { name: "OFFICINE KOROTOUMOU DIARRA", address: "Tominian", commune: "Tominian", ville: "Ségou", phone: "", responsiblePerson: "M. Modibo FOMBA" },
  { name: "OFFICINE TOGUNA", address: "Badiangara", commune: "Badiangara", ville: "Mopti", phone: "", responsiblePerson: "M. GUINDO Issiaka" },
  { name: "OFFIICNE AMANIGNI", address: "Bankass", commune: "Bankass", ville: "Mopti", phone: "", responsiblePerson: "M. Sylvestre TOGO" },
  { name: "OFFICINE SEKOU LARAB", address: "Dioboro", commune: "Djénné", ville: "Mopti", phone: "", responsiblePerson: "M. Abdoul Kader DRAME" },
  { name: "OFFICINE GOREL DÔDÔ", address: "Sofara", commune: "Djénné", ville: "Mopti", phone: "", responsiblePerson: "M. Yaya CISSE" },
  { name: "OFFICINE DU HAIRE", address: "Douentza", commune: "Douentza", ville: "Mopti", phone: "", responsiblePerson: "M. Abdoul SANGARE" },
  { name: "OFFICINE CONCORDE", address: "Douentza", commune: "Douentza", ville: "Mopti", phone: "", responsiblePerson: "M. Adama SAMAKE" },
  { name: "OFFICINE ESPOIR", address: "Koro III", commune: "Koro", ville: "Mopti", phone: "", responsiblePerson: "M. Nouhoum NIANGALY" },
  { name: "OFFICINE DU STADE", address: "Bougoufiè Mopti Mopti M.", commune: "KOÏTA", ville: "Gao", phone: "", responsiblePerson: "ussou" },
  { name: "OFFICINE MAHMOUDOU DIALL", address: "Komoguel 1", commune: "Mopti", ville: "Mopti", phone: "", responsiblePerson: "M. DIALL Mahamoudou" },
  { name: "OFFICINE ASSANA GUINDO", address: "Komoguel 2", commune: "Mopti", ville: "Mopti", phone: "", responsiblePerson: "M. GUINDO Assana" },
  { name: "OFFICINE ABDERRAMANE MAÏGA", address: "Sévaré", commune: "Mopti", ville: "Mopti", phone: "", responsiblePerson: "M. MAÏGA Abderramane" },
  { name: "OFFICINE BONGO", address: "Sévaré", commune: "Mopti", ville: "Mopti", phone: "", responsiblePerson: "M. DOLO Diadié dit Moïse" },
  { name: "OFFICINE DU MOTEL", address: "Sévaré", commune: "Mopti", ville: "Mopti", phone: "", responsiblePerson: "M. TRAORE Adama" },
  { name: "OFFICINE FASO KENEYA", address: "Sévaré", commune: "Mopti", ville: "Mopti", phone: "", responsiblePerson: "M. KONIPO Abdoulaye" },
  { name: "OFFICINE DE L'AMITIE", address: "Sévaré", commune: "Mopti", ville: "Mopti", phone: "", responsiblePerson: "Dr Mariam SAMAKE" },
  { name: "OFFICINE FATOUMATA DAMA", address: "Monsikoro", commune: "Mopti", ville: "Mopti", phone: "", responsiblePerson: "M. Sekou NIANGALY" },
  { name: "OFFICINE BINTA NADIO", address: "Konna", commune: "Mopti", ville: "Mopti", phone: "", responsiblePerson: "M. Mamadou M.S KAMPO" },
  { name: "OFFICINE DE LA VENISSE", address: "Komoguel II", commune: "Mopti", ville: "Mopti", phone: "", responsiblePerson: "M. Moussa Mamadou DIALLO" },
  { name: "OFFICINE TIGUE GUIROU", address: "Komoguel II", commune: "Mopti", ville: "Mopti", phone: "", responsiblePerson: "M. Caleb GUIROU" },
  { name: "OFFICINE SALAM", address: "Médina-Coura-Mopti", commune: "Mopti", ville: "Mopti", phone: "", responsiblePerson: "M. Alpha Boubacra KOUREISSI" },
  { name: "OFFICINE MASSABA KEÏTA", address: "Socoura", commune: "Mopti", ville: "Mopti", phone: "", responsiblePerson: "M. Alassane TANGARA" },
  { name: "OFFICINE BINTI BAYE", address: "Sévaré Logements Sociaux", commune: "Mopti", ville: "Mopti", phone: "", responsiblePerson: "Mme Lalla DOUCOURE" },
  { name: "OFFICINE DIAWARALA", address: "Sévaré, Route de Mopti", commune: "Mopti", ville: "Mopti", phone: "", responsiblePerson: "M. Youssouf DIAWARA" },
  { name: "OFFICINE TENENKOISE", address: "Ténenkou", commune: "Ténenkou", ville: "Mopti", phone: "", responsiblePerson: "M. TOURE Youmma DIARRA" },
  { name: "OFFICINE YATTPHARMA", address: "Diré", commune: "Diré", ville: "Tombouctou", phone: "", responsiblePerson: "Mme Awa Aly YATTARA" },
  { name: "OFFICINE INCONNU", address: "Quartier Alphahou", commune: "Goundam", ville: "Tombouctou", phone: "", responsiblePerson: "M. Hamane Ibrahima TOURE" },
  { name: "PHARMACIE AWA DIEMA", address: "Niafunké", commune: "Niafunké", ville: "Tombouctou", phone: "", responsiblePerson: "M. Mamadou Dabou TRAORE" },
  { name: "OFFICINE JOUR ET NUIT", address: "Badjindé", commune: "Tombouctou", ville: "Tombouctou", phone: "", responsiblePerson: "M. HAÏDARA Moulaye Darhamane" },
  { name: "OFFICINE DE LA CITE", address: "Sarékéïna", commune: "Tombouctou", ville: "Tombouctou", phone: "", responsiblePerson: "M. DEMBELE Sory Ibrahima" },
  { name: "OFFICINE TANGUI", address: "Hamabangou", commune: "Tombouctou", ville: "Tombouctou", phone: "", responsiblePerson: "M. Attaher Ag Mohamed AHMED" },
  { name: "OFFICINE RAHMAH", address: "Ansongo Quartier Admin", commune: "Ansongo", ville: "Gao", phone: "", responsiblePerson: "Mlle Hariratou Harouna CISSE" },
  { name: "OFFICINE AMOLI", address: "Bourem", commune: "Bourem", ville: "Gao", phone: "", responsiblePerson: "M. Agassoumane ABDRAHAMANE" },
  { name: "OFFICINE ATTIBEYE", address: "7e Quartier (Sossokoïra)", commune: "Gao", ville: "Gao", phone: "", responsiblePerson: "M. MAÏGA Ousmane Farka" },
  { name: "OFFICINE BAKARY KONARE", address: "Farandjiré", commune: "Gao", ville: "Gao", phone: "", responsiblePerson: "M. Bakary KONARE" },
  { name: "OFFICINE PASTEUR", address: "Saneye", commune: "Gao", ville: "Gao", phone: "", responsiblePerson: "M. SOMBORO Antandou Kassoum Jean Martin" },
  { name: "OFFICINE GOMNY", address: "7ème Quartier (Sossokoïra)", commune: "Gao", ville: "Gao", phone: "", responsiblePerson: "M. IBRAHIM Moussa" },
  { name: "OFFICINE FOGHAS", address: "Dioulabougou", commune: "Gao", ville: "Gao", phone: "", responsiblePerson: "M. Almahadi Mohamed" },
  { name: "OFFICINE RHAMA", address: "Djoulabougou", commune: "Gao", ville: "Gao", phone: "", responsiblePerson: "M. Abdoul Aziz ILIASSE" },
  { name: "OFFICINE MOHAMED DICKO", address: "Aljanabandia", commune: "Gao", ville: "Gao", phone: "", responsiblePerson: "M. Mohamed DICKO" },
  { name: "OFFICINE SONI ALI BER", address: "Gao Château Secteur I", commune: "Gao", ville: "Gao", phone: "", responsiblePerson: "M. Minkaïla Djibrilla MAÏGA" },
  { name: "OFFICINE ABDEL KADER EL ANSARI", address: "Quartier Château", commune: "Gao", ville: "Gao", phone: "", responsiblePerson: "M. Diakaria KONATE" },
  { name: "OFFICINE ADAM & EVE", address: "Farandjireye Gao", commune: "Gao", ville: "Gao", phone: "", responsiblePerson: "M. Ousmane COULIBALY" },
  { name: "OFFICINE Houa BENGALY", address: "Farabana Kati Koulikoro", commune: "M.", ville: "Gao", phone: "", responsiblePerson: "ussou OUATTARA" },
  { name: "OFFICINE ASSAP", address: "Souban", commune: "Koulikoro", ville: "Koulikoro", phone: "", responsiblePerson: "M. Mamadou BALAM" },
  { name: "OFFICINE LAC TELE", address: "Sossowale", commune: "Goundam", ville: "Tombouctou", phone: "", responsiblePerson: "M. Hamadoun Madiou TRAORE" },
  { name: "OFFICINE MAH CHA ALLAH", address: "Kalaban coro nérécoro Kalaban", commune: "coro", ville: "Koulikoro", phone: "", responsiblePerson: "M. Ousmane CISSE" },
  { name: "OFFICINE CHECHIO", address: "Niamana Logements Sociaux ATTBougou", commune: "Kalaban-coro", ville: "Koulikoro", phone: "", responsiblePerson: "M. Lassina TRAORE" },
  { name: "OFFICINE NOUMOUSSA", address: "Faladiè Socoura", commune: "Commune VI", ville: "Bamako", phone: "", responsiblePerson: "M. Mamadou SAMAKE" },
  { name: "OFFICINE AMINATA DEMBELE", address: "Golobougou", commune: "Kati", ville: "Koulikoro", phone: "", responsiblePerson: "Mme Ouassa DEMBELE" },
  { name: "OFFICINE ALHOUSSOUNA DICKO", address: "Lakamané", commune: "Diéma", ville: "Kayes", phone: "", responsiblePerson: "M. Sekou DEMBELE" },
  { name: "OFFICINE Mariam SAMAKE", address: "Fombabougou Dbiso Da", commune: "Moribabougou", ville: "Koulikoro", phone: "", responsiblePerson: "Mme Kadiatou dite Kabacoro SAMAKE" },
  { name: "OFFICINE LE GOURMA", address: "Boulkassoumbougou", commune: "Commune I", ville: "Bamako", phone: "", responsiblePerson: "Mme Kadiatou KAMIAN" },
  { name: "OFFICINE KANOU", address: "Hippodrome", commune: "Commune II", ville: "Bamako", phone: "", responsiblePerson: "M. Adama GOÏTA" },
  { name: "OFFICINE YEHIA MOULAYE", address: "Tombouctou", commune: "Tombouctou", ville: "Tombouctou", phone: "", responsiblePerson: "M. Mahamane Abdoulaye HAÏDARA" },
  { name: "OFFICINE BA TENIMBA", address: "Cinzana Gare", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "Moussa Sékou BAGAYOKO" },
  { name: "OFFICINE KILOMETRE 23", address: "Niono Kilomètre 23", commune: "Niono", ville: "Ségou", phone: "", responsiblePerson: "M. Mohamed dit Odiouma SIDIBE" },
  { name: "OFFICINE MARIAM TOURE", address: "Siribala Extension", commune: "Siribala", ville: "Ségou", phone: "", responsiblePerson: "Mme Fadimatou COULIBALY" },
  { name: "OFFICINE Fanta KEÏTA", address: "Naréna", commune: "Naréna", ville: "Koulikoro", phone: "", responsiblePerson: "M. Chiaka COULIBALY" },
  { name: "OFFICINE BATOUMA BAYA", address: "Sébénicoro", commune: "Commune IV", ville: "Bamako", phone: "", responsiblePerson: "M. Koniko KAMATE" },
  { name: "OFFICINE DILLY", address: "Kita", commune: "Samédougou", ville: "Kayes", phone: "", responsiblePerson: "M. Modibo KONATE" },
  { name: "OFFICINE ROKIA SAMAKE", address: "Loubougoula", commune: "Loubougoula", ville: "Sikasso", phone: "", responsiblePerson: "M. Tidiane COULIBALY" },
  { name: "OFFICINE HANFIZO", address: "Bougoula hameau", commune: "Sikasso", ville: "Sikasso", phone: "", responsiblePerson: "Mme Damousso KONE" },
  { name: "OFFICINE MIEUX VIVRE", address: "Mancourani", commune: "Sikasso", ville: "Sikasso", phone: "", responsiblePerson: "Mme Kadidia KONE Epouse SAADE" },
  { name: "OFFICINE TELAKURA", address: "Djicoroni-Para", commune: "Commune IV", ville: "Bamako", phone: "", responsiblePerson: "Ibrahim Halidou MAÏGA" },
  { name: "OFFICINE AÏCHA TOLO", address: "Baco-djicoroni ACI", commune: "Commune V", ville: "Bamako", phone: "", responsiblePerson: "M. Mamoudou TOLO" },
  { name: "OFFICINE SAGABARI", address: "Sagabari", commune: "Gadougou", ville: "Kayes", phone: "", responsiblePerson: "M. Moussa GOÏTA" },
  { name: "OFFICINE ANCHATA TRAORE", address: "Souleymanebougou ACI", commune: "Kati", ville: "Koulikoro", phone: "", responsiblePerson: "M. Boubacar DIAMOUTENE" },
  { name: "OFFICINE M'BA ASSITAN SANGARE", address: "Nioro du sahel", commune: "Nioro", ville: "Kayes", phone: "", responsiblePerson: "M. Moussa KONE" },
  { name: "OFFICINE TRONE", address: "Dianéguéla Cité", commune: "Commune VI", ville: "Bamako", phone: "", responsiblePerson: "M. Ibrahim DEMBELE" },
  { name: "OFFICINE DJA", address: "Faladiè Socoro", commune: "Commune VI", ville: "Bamako", phone: "", responsiblePerson: "M. Issa MALET" },
  { name: "OFFICINE SANKORE", address: "N'Tomikorobougou", commune: "Commune III", ville: "Bamako", phone: "", responsiblePerson: "M. Blaly DEMBELE" },
  { name: "PHARMACIE ALIMA COULIBALY", address: "Yirimadio 330 logements sociaux", commune: "Commune VI", ville: "Bamako", phone: "", responsiblePerson: "Mme Fatoumata TANGARA" },
  { name: "PHARMACIE AMARY DAOU", address: "Missira", commune: "Ségou", ville: "Ségou", phone: "", responsiblePerson: "Cheick Kader SANGARE" },
  { name: "OFFICINE OUMOU N'DIAYE", address: "Wayerma I", commune: "Sikasso", ville: "Sikasso", phone: "", responsiblePerson: "Maïmouna BERTHE" },
  { name: "OFFICINE ZAMPEFOUN", address: "Sanoubougou I", commune: "Sikasso", ville: "Sikasso", phone: "", responsiblePerson: "Souleymane SANOGO" },
  { name: "OFFICINE KONIBA PLEAH", address: "Légal-Ségou", commune: "Kayes", ville: "Kayes", phone: "", responsiblePerson: "Fatoumata Bintou PLEAH" },
  { name: "OFFICINE DJOLE DIARRA", address: "Fadjiguila", commune: "Commune I", ville: "Bamako", phone: "", responsiblePerson: "Kassoumou Falibo DIARRA" },
  { name: "OFFICINE ASSITAN SOUMANO", address: "Djicoroni-Coura", commune: "Kati", ville: "Koulikoro", phone: "", responsiblePerson: "Ousmane KOUYATE" },
  { name: "OFFICINE BINKORO KONE", address: "Kita", commune: "Kita", ville: "Kayes", phone: "", responsiblePerson: "Abdou Salam BAH" },];